version: "3"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
     sh -c "python manage.py runserver 0.0.0.0:8000"
  client:
      build:
        context: ./frontend
      volumes:
        - /app/node_modules
        - ./frontend:/app
      ports:
        - "3000:3000"
  